// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQj_e80iihovveT9ABlZFMr5431nTofrg',
    appId: '1:169543119420:web:37fbbfa069a28cc1054939',
    messagingSenderId: '169543119420',
    projectId: 'gbv-awareness',
    authDomain: 'gbv-awareness.firebaseapp.com',
    storageBucket: 'gbv-awareness.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv9nZI3AejRCbMRQa0rD7pPv22jHSno_Q',
    appId: '1:169543119420:android:8d9f9a59f58987f0054939',
    messagingSenderId: '169543119420',
    projectId: 'gbv-awareness',
    storageBucket: 'gbv-awareness.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKBMZWGqCc3N0dP69yjqoAMu1P8iiKPEo',
    appId: '1:169543119420:ios:8839dd40396c871a054939',
    messagingSenderId: '169543119420',
    projectId: 'gbv-awareness',
    storageBucket: 'gbv-awareness.firebasestorage.app',
    iosBundleId: 'com.example.gbvAwareness',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKBMZWGqCc3N0dP69yjqoAMu1P8iiKPEo',
    appId: '1:169543119420:ios:8839dd40396c871a054939',
    messagingSenderId: '169543119420',
    projectId: 'gbv-awareness',
    storageBucket: 'gbv-awareness.firebasestorage.app',
    iosBundleId: 'com.example.gbvAwareness',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQj_e80iihovveT9ABlZFMr5431nTofrg',
    appId: '1:169543119420:web:ea7e2d6f01a3099b054939',
    messagingSenderId: '169543119420',
    projectId: 'gbv-awareness',
    authDomain: 'gbv-awareness.firebaseapp.com',
    storageBucket: 'gbv-awareness.firebasestorage.app',
  );

}